# Generated by Django 4.2.6 on 2023-11-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
