# Generated by Django 4.2.6 on 2023-11-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmr_app', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('test_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('test_text', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Test2',
            },
        ),
    ]
