# Generated by Django 3.2.23 on 2023-11-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
